# fly.toml app configuration file generated for challenge-lively-forest-2663 on 2024-10-18T03:18:43-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'challenge-lively-forest-2663'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80